version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commonsense
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend        # backend フォルダをビルドコンテキストに
      dockerfile: Dockerfile    # その中の Dockerfile を使う
    depends_on:
      - db
    environment:
      # pg_isready 用にホストを環境変数として渡す例
      DB_HOST: db
      DB_PORT: 5432
      # SQLAlchemy 用の接続文字列
      DATABASE_URL: postgresql://postgres:postgres@db:5432/commonsense
    ports:
      - "8000:8000"
    # ENTRYPOINT は Dockerfile 側で指定済みなので省略可

volumes:
  postgres_data: